### ISSUE TITLE
Refine auto-tags feature to simplify ambiguous tag filtering cases

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1188]
- [ ] Rename current auto-tag `name` to `fullname`
- [ ] Add a new auto-tag for `name`
- [ ] Add unit tests
- [ ] Update docs
- [ ] Update built-in workloads
- [ ] Update blogs if needed
- [ ] Add a contextual warning for cases where a tag filter with name *name* is used.

# Current State

Consider a user has a workload template like this:

```
blocks:
 yakshaver:
  ops:
   yakshaver-1:
    ...
   shornyak-1:
    ...
```

## current auto-tags

NB automatically adds tags to this which are virtual and not user settable, equivalent to this:
```
blocks:
 yakshaver:
  ops:
   yakshaver-1:
    tags:
     block: yakshaver
     name: yakshaver--yakshaver-1
    ...
   shornyak-1:
    tags:
     block: yakshaver
     name: yakshaver--shornyak-1
    ...
```
Notice that the name 'yakshaver--yakshaver-1' is an expansion of the pattern `<blockname>--<opname>`. This makes the "name" tag globally unique within the document as a side-effect of unique block names and op names within a block.

However, we have found that this creates a confusing usage pattern for users who tag filter with regexes. Case in point:
The tag filter `tags="name:yakshaver.*"` matches **all** op templates. This is counter intuitive since the tag named *name* is strongly suggestive of the op name. When the blockname prefix matches an op name prefix, such patterns only create more confusion.

# Alternative

An alternative to this is to simplify the usage of auto-tags, so that they simply contain the values present in the yaml structure. This means that faceted filtering of tag value would work as expected. It is also a simpler case for matching either or block and op template name, since you can combine them easily. In order to allow the previous matching behavior, another concatenated form could be provided under the tag name `fullname`, short for *fully-qualified name*.

## new auto-tags

With these changes, the original workload template would be equivalent to this after being loaded:

```
blocks:
 yakshaver:
  ops:
   yakshaver-1:
    tags:
     block: yakshaver
     op: yakshaver-1
     fullname: yakshaver--yakshaver-1
    ...
   shornyak-1:
    tags:
     block: yakshaver
     op: shornyak-1
     fullname: yakshaver--shornyak-1
    ...
```
With this form, the ambiguity around how to match is removed for the most obvious tag names.

**Matching all templates in a block**

    tags=block:yakshaver

**Matching all templates with an op name pattern**

    tags=op:yakshaver.*

**Matching all templates in a block with an op name pattern**

    tags=block:yakshaver,op:yakshaver.*

# Compatibility

This is not backwards-compatible, and may break extant test definitions. There isn't a simple way to continue using the `name` auto-tag without breaking previous workload templates. The behavior is too unintuitive and ambiguous to leave in as-is. Thus, the name `op` is selected, and seems a more desirable (aligned with extant structure) anyway.

At the very least, users who have any tag filter including `name` should be given an error that is specific to the change so that they can update it.

**Comment by jshook** [comment]
This may have been fixed in the current code. It needs to be verified and a test added in any case.

**Comment by dave2wave** [comment]
block, name, and op tags are automatically generated and available.
