### ISSUE TITLE
Add strict mode for well-formed names in NB identifiers

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1808]
At some point in the near future, names which can cause issue with downstream metrics systems should be
avoided completely. This means that any name which includes dashes, or otherwise does not conform to a valid open metrics label name or value should cause an error.

As the first step, places where users can provide these labels should be enabled with advisory warnings indicating that the format will be deprecated, suggesting an alternate example form.

This includes these places at least:

- [x] * workload parameters - `yaml`
- [x] * template variables - `StrInterpolator`
- [x] * label names and values
- [x] * tag names - `yaml`
- [ ] * op field properties which may be included in metrics or logging - `yaml`
- [x] * activity names, container names, container variable names - `yaml`

**Comment by dave2wave** [comment]
There are quite a few locations mentioned. It would help to point to code where some of these checks could be made.

An approach to this would be to create a validator class that would be a static singleton like NBEnvironment. Then each type of name could be tested in the appropriate piece of code.

**Comment by dave2wave** [comment]
@jshook does this issue depend on the completion of #12 ?

**Comment by jshook** [comment]
Issue #12 is part of this, however it is mostly for the cohesion in docs. In other words, we want the behavior of this validator logic to be very well defined for users. However, we should not relax this because it is a strong requirement for sane downstream metrics. So in terms of what is validated at what level, it should at least be documented as a validation that occurs even for relaxed mode.

**Comment by dave2wave** [comment]
@sahankj2000 identified the class that ought to be modified in their closed PR - `StrInterpolator`:

I think that we can consider code like this:

```java
import org.apache.commons.text.StringSubstitutor;
import org.apache.commons.text.lookup.StringLookup;

public class StringModifierWithSubstitutor {
    public static void main(String[] args) {
        String original = "example-string-to-modify";

        // Create a custom lookup to replace '-' with '_'
        StringLookup lookup = key -> key.replace("-", "_");

        // Set up the StringSubstitutor with the custom lookup
        StringSubstitutor substitutor = new StringSubstitutor(lookup);
        
        // Perform the substitution
        String modified = substitutor.replace(original);

        // Check if modification happened
        if (!original.equals(modified)) {
            System.out.println("Modification occurred. Modified string: " + modified);
        } else {
            System.out.println("No modification was needed.");
        }
    }
}
```

We will need to have this happen according to the advisory levels.

**Comment by dave2wave** [comment]
`yaml` work starts from within `OpsLoader.java`
```java
       // TODO: itemize inline to support ParamParser                                                                                                                                 

        OpsDocList layered = new OpsDocList(rawOpsDocList);

        transformer.checkpointAccesses().forEach((k, v) -> {
            layered.addTemplateVariable(k, v);
            params.remove(k);
        });
```

**Comment by dave2wave** [comment]
Knowledge grows and it looks like `ConfigMap` is where checking and testing needs to be added particularly in the following method:
```java
 public void assertValidConfig(Map<String, ?> config) {
        ConfigModel expanded = expand(this, config);
        expanded.assertRequiredFields(config);
        expanded.assertNoExtraneousFields(config);
        expanded.assertDistinctSynonyms(config);
    }
```

**Comment by dave2wave** [comment]
Ops fields will require analysis of mapped op statements.
