### ISSUE TITLE
INITIATIVE: Assemble minimum feature set for simple vector query testing by anybody.

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#2002]
We need a focused effort on preparing a simple and repeatable user experience for testing vector stores.
Specifically, this should include:
- [ ] A canonical dataset which is publicly accessible and for which we provide large KNN answer key.
- [ ] Console output which is simple and direct for an ongoing test and the key results.
- [ ] Associated examples and documentation.
- [ ] UAT verified workloads for all supported vector systems.
