### ISSUE TITLE
Upgrade the transport for prometheus metrics collection

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#248]
The current form of using graphite by default even when sending data to prometheus is not robust. It creates additional complexity for both the prometheus and the grafana integrations. Labels/Tags are necessary semantic features at the protocol and API level in order to simplify and stabilize the metrics reporting interface going forward.

In any case, the method should be possible to automate for push-button standup of metrics collection and dashboarding. This should include both the locally hosted topology as well as hub-spoke or other topologies which may be used in higher scale scenarios. The commands to configure any of these topologies should be simple and obvious.

One of two possible approaches can be used:

"push"

Add a stub listener to a prometheus docker so that the batch interface to prometheus is exposed as a simple push interface, protected by a simple API key mechanism. This means that the test client is allowed to control the timing and provenance of data as it should, given that specific timing semantics are used to enable metrics visibility for advanced analysis methods. The trade-off is that the "last data point" in prometheus will hang around, but, at least for nosqlbench, this doesn't seem particularly different than the usually preferred way of having prometheus drive all data collection.

"poll"

Add a prometheus target service on the nosqlbench client. This would require the nosqlbench client to publish a web service which hosts metrics while it is running. This is closer to the preferred way of providing data sources for prometheus, but it takes control away from users who want to establish their own update frequency for near-time visibility. It also means that updates to a topology for additional data sources would require active reconfiguration of the prometheus instance. Getting around this would require yet another change to the prometheus docker to allow for an external configuration service.

## Implementation plan, after further research:

A requirement for discretely labeled data on short sampling windows has bumped this up in priority. Specifically, the ability to sample short time windows and label them accurately with specific properties will enable a new type of performance study.

Recent suggestions and research has yielded a better design for this. It has been broken out into smaller pieces and assigned to a milestone.

**Comment by jshook** [comment]
A requirement for discretely labeled data on short sampling windows has bumped this up in priority. Specifically, the ability to sample short time windows and label them accurately with specific properties will enable a new type of performance study.

Recent suggestions and research has yielded a better design for this:
- [ ] Adapt metrics to use label sets internally.
- [ ] Ensure metrics are labeled with the previous hierarchic values for scenario, activity, etc.
- [ ] Bundle victoria metrics orchestration rules into the docker helper.
- [ ] Implement an openmetrics push reporter.
- [ ] Rewire NBCLI logic to use the victoria metrics path with a client-push reporter and full label support.
- [ ] Re-configure [a new] grafana dashboard to use the more direct and simpler labeling scheme.
- [ ] Update docs on how to use the new dashboard, what the labels mean, and how to customize them per scenario.
